### ISSUE TITLE
Key devices on id not name

### ISSUE THREAD

**Issue by daltskin** [daltskin/SmartThingsTerminal#8]
It's not crashing anymore but it gives the following error:
> Unknown error calling API: An item with the same key has already been added.
Key: XXX iPhone

_Originally posted by @rboy1 in https://github.com/daltskin/SmartThingsTerminal/issues/6#issuecomment-656273658_

**Comment by rboy1** [comment]
This is an issue with the ST new app. It automatically creates a mobile presence device but it doesn’t show the device and hence there’s no way to change the name. 
So if you’re using the Classic app and the new app at the same time ST will create two presence sensors with the same name. 

If you’re creating a map consider using the device ID instead which is unique.

**Comment by daltskin** [comment]
@rboy1 latest release should fix this: https://github.com/daltskin/SmartThingsTerminal/releases/tag/0.12.1

**Comment by rboy1** [comment]
It working now but it's still crashes on other operations. Here are 2 instances:

1. When I click on full screen and then I click on a menu item using a mouse
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartThingsTerminal.Scenarios.Devices.UpdateSettings[T](Object selectedItem)
   at SmartThingsTerminal.Scenario.<>c__DisplayClass68_0`1.<GetClassListView>b__0(ListViewItemEventArgs args)
   at Terminal.Gui.ListView.OnSelectedChanged()
   at Terminal.Gui.ListView.MouseEvent(MouseEvent me)
   at Terminal.Gui.View.OnMouseEvent(MouseEvent mouseEvent)
   at Terminal.Gui.Application.ProcessMouseEvent(MouseEvent me)
   at Terminal.Gui.WindowsDriver.Terminal.Gui.IMainLoopDriver.MainIteration()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Boolean closeDriver)
   at SmartThingsTerminal.Scenario.Run()
   at SmartThingsTerminal.Program.Init(Options opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SmartThingsTerminal.Program.Main(String[] args)

2. When keep the down arrow key pressed to scroll through the devices quickly:
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartThingsTerminal.Scenarios.Devices.UpdateSettings[T](Object selectedItem)
   at SmartThingsTerminal.Scenario.<>c__DisplayClass68_0`1.<GetClassListView>b__0(ListViewItemEventArgs args)
   at Terminal.Gui.ListView.OnSelectedChanged()
   at Terminal.Gui.ListView.MoveDown()
   at Terminal.Gui.ListView.ProcessKey(KeyEvent kb)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.View.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Toplevel.ProcessKey(KeyEvent keyEvent)
   at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke)
   at Terminal.Gui.WindowsDriver.Terminal.Gui.IMainLoopDriver.MainIteration()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Boolean closeDriver)
   at SmartThingsTerminal.Scenario.Run()
   at SmartThingsTerminal.Program.Init(Options opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SmartThingsTerminal.Program.Main(String[] args)

I also noticed that when the full screen button is pressed on the command prompt the console goes full screen but it the cursor loses track/context of it's location which then renders it unsable until you quit and restart again.

**Comment by rboy1** [comment]
Hmm, I think I know why the second crash is happening. It's not the keypress but when it reached some devices it crashes. I have multiple locations in my account, if I select a device from a different location (any device) it crashes with this trace )this one happened when I used a mouse to select a device in a non default location:
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SmartThingsTerminal.Scenarios.Devices.UpdateSettings[T](Object selectedItem)
   at SmartThingsTerminal.Scenario.<>c__DisplayClass68_0`1.<GetClassListView>b__0(ListViewItemEventArgs args)
   at Terminal.Gui.ListView.OnSelectedChanged()
   at Terminal.Gui.ListView.MouseEvent(MouseEvent me)
   at Terminal.Gui.View.OnMouseEvent(MouseEvent mouseEvent)
   at Terminal.Gui.Application.ProcessMouseEvent(MouseEvent me)
   at Terminal.Gui.WindowsDriver.Terminal.Gui.IMainLoopDriver.MainIteration()
   at Terminal.Gui.MainLoop.MainIteration()
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Boolean closeDriver)
   at SmartThingsTerminal.Scenario.Run()
   at SmartThingsTerminal.Program.Init(Options opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SmartThingsTerminal.Program.Main(String[] args)

**Comment by daltskin** [comment]
@rboy1 thanks for raising this.  However, I've not been able to recreate this issue today - I also have multiple locations (2).

I've added some additional error handling and creating a new issue to track this: https://github.com/daltskin/SmartThingsTerminal/issues/13 - so the next release will hopefully address this (lmk if it doesn't).

**Comment by rboy1** [comment]
I only see the osx binary builds for 0.12.4 and don't see any win 10 builds

**Comment by daltskin** [comment]
Arch the build failed for some reason. Just re-run, binaries should be there now.

Sent from my telekommunikator.

________________________________

**Comment by daltskin** [comment]
Builds are now available.

**Comment by rboy1** [comment]
Working fine now, no crashes and the data is showing up. On suggestion, it would be nice to sort the list by name since with 300 devices it can get cumbersome to locate them

**Comment by daltskin** [comment]
@rboy1 Thanks for the feedback - just done this tonight in the latest release :)
